from textnode import TextNode, TextType

def split_nodes_delimiter(old_nodes: list[TextNode], delimiter: str, text_type: TextType) -> list[TextNode]:
    new_nodes = []
    for old_node in old_nodes:
        if old_node.text_type is not TextType.TEXT:
            new_nodes.append(old_node)
            continue
        
        if old_node.text.count(delimiter) %2 == 1:
                raise Exception(delimiter + " not 2 times")
        
        splitted_nodes = old_node.text.split(delimiter)        
        
        for i, splitted_node in enumerate(splitted_nodes):
            if splitted_node == "":
                continue  # Skip any empty strings generated by the split
                
            # Even indices are ALWAYS regular text, odd indices are ALWAYS the formatted type
            if i % 2 == 0:
                new_nodes.append(TextNode(splitted_node, TextType.TEXT))
            else:
                new_nodes.append(TextNode(splitted_node, text_type))
    
    return new_nodes